# -*- coding: utf-8 -*-
"""英文站核心頁：首頁、中心介紹、醫師、團隊、交通、初診。
事實來源：官方名冊查證（執照 18759、FMCSA 5497424313）、客戶英文站盤點、GBP。
刻意不提 QME —— 加州 DWC 名冊查無此人，客戶確認前不寫進新內容。"""

WHY_EN = [
 ("In practice since","1988 — 38 years","Same practitioner, same Oakland Chinatown block since 1988. Long enough to have seen most presentations more than once.",False),
 ("Languages","Cantonese · Mandarin · Taiwanese · English","From history-taking through to explaining the plan, in the language you are most comfortable in. You do not need to bring your own interpreter.",False),
 ("On-site imaging","Digital X-ray, same visit","When imaging is clinically indicated it is taken here, so you are not sent to a separate imaging centre and back.",False),
 ("Getting here","5-minute walk from Lake Merritt BART","In the Madison professional building in downtown Oakland. Building and street parking both available.",False),
]

PAGES = [

# ── 首頁 ─────────────────────────────────────────
{
 "slug":"", "nap":True, "cta_bg":"alt", "faq_bg":"",
 "hero":("storefront","The CarePlus Chiropractic storefront at 212 9th Street in Oakland Chinatown"),
 "title":"Chiropractor in Oakland Chinatown｜CarePlus Chiropractic · Dr. Stewart Chen",
 "desc":"Chiropractic care in Oakland Chinatown since 1988. Spinal adjustment, acupuncture, auto accident and work injury rehabilitation, and DOT/CDL driver physicals at $95. Cantonese, Mandarin, Taiwanese and English. 212 9th Street Suite 103. 510-465-7982.",
 "h1":"Chiropractic care in Oakland Chinatown since 1988",
 "answer":"CarePlus Chiropractic Health Center has practised at 212 9th Street in Oakland Chinatown since 1988. Dr. Stewart Chen, D.C. provides spinal adjustment, acupuncture, auto accident and work injury rehabilitation, and DOT/CDL driver physicals at $95. Cantonese, Mandarin, Taiwanese and English spoken. Lake Merritt BART is a five-minute walk.",
 "blocks":[
  {"t":"routes","eyebrow":"Where to start","h2":"What brings you in?",
   "lede":"Pick the closest description and we will take you to the details that matter for your situation.",
   "items":[
    ("/services/auto-injury/","I was in a car accident","Neck, back or shoulder pain after a collision, including delayed symptoms. Billing is usually through the claim, not out of pocket.","How this works →"),
    ("/services/work-injury/","I was hurt at work","Assessment and treatment under California workers' compensation, plus help with the paperwork.","What to expect →"),
    ("/dot-physical/","I need a DOT physical","$95, report the same day, performed by a certified medical examiner on the FMCSA National Registry.","Book a physical →"),
    ("/services/","Something hurts and I don't know why","Back, neck, shoulder, headache, numbness or tingling. We start by finding out what is actually going on.","See all services →")]},
  {"t":"facts","bg":"alt","eyebrow":"Verifiable credentials","h2":"Both of these are on public government registers",
   "lede":"The numbers below can be checked directly. Links are underneath.",
   "sources":["dca_search","fmcsa_srch"],
   "items":[
    ("State of California","Licensed Doctor of Chiropractic · No. 18759","Issued by the California Board of Chiropractic Examiners under the name CHEN, STEWART GO. Verified September 2026 as <strong>VALID</strong> through 31 March 2027, with no disciplinary or secondary status on record.",True),
    ("U.S. Department of Transportation","Certified Medical Examiner · No. 5497424313","Listed on the FMCSA National Registry of Certified Medical Examiners as Stewart Chen, D.C. at this clinic address. Issued 22 July 2019, valid through 22 July 2029. A commercial driver's physical is only valid if performed by an examiner on this register.",True),
    ("Palmer College of Chiropractic","Doctor of Chiropractic, 1987","Also serves as adjunct clinical faculty at Palmer College.",False),
    ("Community service","Alameda Health Care District Board","Elected board member since 2020; also serves on the AC Transit district parcel tax oversight committee since 2021. Both are matters of public record.",False)]},
  {"t":"price","eyebrow":"DOT / CDL driver physical","h2":"$95, report the same day",
   "amount":"$95","unit":"per exam · all inclusive",
   "items":["Performed by a DOT certified medical examiner",
            "You leave with the report the same day",
            "We can help submit the report to the DMV",
            "Saturday morning appointments available"],
   "note":"Under FMCSA rules a driver's medical certificate is valid for <strong>up to 24 months</strong>. Conditions such as high blood pressure or diabetes may shorten that to 12 or 3 months.",
   "sources":["fmcsa_reg","fmcsa_srch"],
   "stamp":"Price current as of September 2026. Additional tests, if needed, are quoted before they are carried out."},
  {"t":"equip","eyebrow":"On site","h2":"Equipment available in the treatment rooms",
   "items":["Digital X-ray","Spinal traction","Ultrasound therapy","Electrical stimulation","Microcurrent",
            "Hot and cold therapy","Cupping","G5 percussion massage","Paraffin bath","Vapocoolant stretch",
            "Rehabilitation exercise instruction","Three private treatment rooms"]},
  {"t":"reviews","bg":"alt","eyebrow":"Patient reviews","h2":"Google Business Profile rating",
   "sources":[("int","/reviews/","More patient feedback →")],
   "items":[("Quick process, and the doctor and staff were all very kind. Highly recommend.","Google review"),
            ("The whole DOT physical took about 35 minutes. Fast and convenient.","Google review · DOT physical"),
            ("Dr. Chen treated my neck injury after a car accident years ago. I only found out later that he also does federal DOT physicals.","Google review")]},
  {"t":"photos","eyebrow":"Inside the clinic","h2":"What the practice actually looks like",
   "lede":"These are photographs of the clinic, not stock images.",
   "items":[("storefront-sign","The bilingual street sign outside the clinic",None),
            ("waiting-room","The waiting room, with the certificate wall behind the seating",None),
            ("exam-room","Examination room with diagnostic equipment and an X-ray viewer",None),
            ("xray-machine","The clinic's digital X-ray unit","No need to travel to a separate imaging centre"),
            ("team","The CarePlus Chiropractic team",None),
            ("patient-files","Patient records accumulated since 1988",None)]},
 ],
 "faq_h2":"Questions people ask before coming in",
 "faqs":[
  ("What should I bring to a first visit, and how long does it take?","<p>Bring photo ID and your insurance card. If this is an auto accident or work injury, also bring the incident report number, the claim number, and your attorney's contact details if you have representation. A first visit covers history, physical examination, digital X-ray where clinically indicated, and an explanation of findings and a proposed plan in the same visit. Allow 45 to 60 minutes.</p>",[("int","/new-patient/","New patient information →")]),
  ("What languages do you speak? Do I need to bring an interpreter?","<p>No. Dr. Chen speaks Cantonese, Mandarin, Taiwanese and English. Staff between them also cover Tagalog and Vietnamese. The consultation and the explanation of your plan can be done entirely in the language you are most comfortable in.</p>",None),
  ("Is the $95 DOT physical the full price?","<p>Yes. $95 covers the examination and the report on the day, and we can help submit it to the DMV. If your situation requires additional testing we will tell you the cost before carrying it out, not afterwards.</p>",[("int","/dot-physical/","About DOT physicals →")]),
  ("How long is a DOT medical certificate valid?","<p>Under FMCSA rules the maximum is 24 months. Where there is high blood pressure, diabetes, sleep apnoea or a similar condition, the examiner may issue a 12-month or 3-month certificate so the condition can be monitored.</p>",["fmcsa_reg"]),
  ("After a car accident, do I have to pay up front?","<p>Usually not. In California, treatment after a collision is commonly paid through the at-fault driver's liability cover, the MedPay provision on your own policy, or on a lien basis where you are represented by an attorney, settled when the claim resolves. Which applies depends on your policy and the case, and we go through it with you at the first visit.</p>",[("int","/insurance/auto-accident/","How auto accident billing works →")]),
  ("Is parking easy? How do I get here on BART?","<p>The clinic is in the Madison professional building in downtown Oakland, between Jackson St and Alice St. From Lake Merritt BART it is a five to seven minute walk. There is parking in the building and on the street. At busy times, allow an extra 10 minutes.</p>",[("int","/contact/","Getting here and parking →")]),
 ],
 "related":[("/services/","All services","Adjustment, acupuncture, rehabilitation"),
            ("/dot-physical/","DOT / CDL physical","$95, same-day report"),
            ("/about/dr-stewart-chen/","Dr. Stewart Chen","Credentials and how to verify them")],
},

# ── 中心介紹 ─────────────────────────────────────
{
 "slug":"about","crumbs":[],"crumb_self":"About","cta_bg":"alt",
 "hero":("team","The CarePlus Chiropractic team in Oakland Chinatown"),
 "title":"About the Clinic｜CarePlus Chiropractic · Oakland Chinatown since 1988",
 "desc":"CarePlus Chiropractic Health Center has served Oakland Chinatown since 1988. Three private treatment rooms, on-site digital X-ray, and care in Cantonese, Mandarin, Taiwanese and English. 212 9th Street Suite 103.",
 "h1":"A neighbourhood practice, in the same place since 1988",
 "answer":"CarePlus Chiropractic Health Center opened in Oakland Chinatown in 1988 and has operated from 212 9th Street ever since. The clinic has three private treatment rooms and on-site digital X-ray. Care is provided in Cantonese, Mandarin, Taiwanese and English, so patients do not need to bring an interpreter.",
 "blocks":[
  {"t":"prose","eyebrow":"How we approach this","h2":"Treating the symptom is not the same as understanding it",
   "html":"""<p>Pain in one place often has its origin somewhere else. A shoulder that will not settle can come from the neck; numbness in the hand can come from the cervical spine rather than the wrist. So the first visit is spent working out where the problem is actually coming from, rather than going straight to treatment.</p>
<p>That means a history, a physical examination including range of motion and a neurological check, and digital X-ray where it is clinically indicated. You are told what was found and what is proposed in the same visit, before anything begins.</p>
<p>Not every patient needs every modality. What is used, and for how long, follows from what the assessment shows.</p>""",
   "sources":["aca","nccih_back"]},
  {"t":"facts","bg":"alt","eyebrow":"Clinic details","h2":"The practical facts",
   "items":[
    ("Established","1988 · 38 years","Opened in Oakland Chinatown and has operated from the same address since.",False),
    ("Address","212 9th Street, Suite 103","Madison professional building, downtown Oakland, CA 94607. Five-minute walk from Lake Merritt BART.",False),
    ("Hours","Mon–Fri 9:00–18:00 · Sat 9:00–12:00","Closed Sunday. By appointment — please call ahead.",False),
    ("Languages","Cantonese · Mandarin · Taiwanese · English","Staff between them also cover Tagalog and Vietnamese.",False)]},
  {"t":"photos","eyebrow":"Inside the clinic","h2":"What the practice looks like",
   "lede":"Photographs taken at the clinic.",
   "items":[("waiting-room","The waiting room, with the certificate wall and seating area",None),
            ("reception","Reception, with the CarePlus Chiropractic lettering on the wall",None),
            ("hallway","The corridor connecting the treatment rooms",None),
            ("exam-room","Examination room with diagnostic equipment and an X-ray viewer",None),
            ("traction-room","Treatment room with a traction table",None),
            ("patient-files","The clinic's patient record files","Paper records accumulated since 1988")]},
  {"t":"equip","bg":"alt","eyebrow":"Equipment","h2":"Available in the treatment rooms",
   "items":["Digital X-ray","Spinal traction","Ultrasound therapy","Electrical stimulation","Microcurrent",
            "Hot and cold therapy","Cupping","G5 percussion massage","Paraffin bath","Vapocoolant stretch",
            "Rehabilitation exercise instruction","Three private treatment rooms"]},
 ],
 "faqs":[
  ("Do I need an appointment?","<p>Yes, the clinic works by appointment. Please call 510-465-7982. If you cannot call right now, use the call-back form on this page and we will ring you during clinic hours.</p>",None),
  ("Do you treat children?","<p>Yes. Assessment for children is different from adults, and the approach is adjusted accordingly.</p>",[("int","/services/pediatric-spine/","Paediatric spinal assessment →")]),
  ("Will I be X-rayed at the first visit?","<p>Only if it is clinically indicated. It is a judgement made during the examination, not something applied to every patient by default. Where imaging is needed it is taken on site during the same visit.</p>",None),
 ],
 "related":[("/about/dr-stewart-chen/","Dr. Stewart Chen","Qualifications, credentials and public record"),
            ("/about/team/","Our team","Front desk, billing and treatment staff"),
            ("/contact/","Visit us","Directions, parking and hours")],
},

# ── 醫師 ─────────────────────────────────────────
{
 "slug":"about/dr-stewart-chen","crumbs":[("About","/about/")],"crumb_self":"Dr. Stewart Chen",
 "person_schema":True,"cta_bg":"alt",
 "title":"Dr. Stewart Chen, D.C.｜California Licence 18759 · DOT Certified Medical Examiner",
 "desc":"Dr. Stewart Chen, D.C. earned his Doctor of Chiropractic from Palmer College in 1987 and has practised in Oakland Chinatown since 1988. California licence 18759, valid through March 2027. FMCSA certified medical examiner 5497424313.",
 "h1":"Dr. Stewart Chen, D.C.",
 "answer":"Dr. Stewart Chen, D.C. earned his Doctor of Chiropractic from Palmer College of Chiropractic in 1987 and has practised in Oakland Chinatown since 1988. He holds California chiropractic licence 18759, valid through 31 March 2027, and is a certified medical examiner on the FMCSA National Registry. He speaks Cantonese, Mandarin, Taiwanese and English.",
 "blocks":[
  {"t":"facts","eyebrow":"Verifiable credentials","h2":"Everything below can be checked on a public register",
   "lede":"We have put the lookup links underneath. Please verify them yourself.",
   "sources":["dca_search","fmcsa_srch","palmer"],
   "items":[
    ("State of California","Licensed Doctor of Chiropractic · No. 18759","Issued by the California Board of Chiropractic Examiners, registered name CHEN, STEWART GO. Checked September 2026: status <strong>VALID</strong>, expiring 31 March 2027, secondary status none — no discipline, probation or restriction on record. Search licence number 18759 at the California Department of Consumer Affairs to confirm.",True),
    ("U.S. Department of Transportation","Certified Medical Examiner · No. 5497424313","Listed on the FMCSA National Registry as Stewart Chen, D.C. at this clinic address. Issued 22 July 2019, valid through 22 July 2029. Searching that number on the registry returns this practice.",True),
    ("Palmer College of Chiropractic","Doctor of Chiropractic, 1987","Undergraduate study at Northwest Missouri State University. Manipulation Under Anaesthesia training at Texas Chiropractic College. Currently adjunct clinical faculty at Palmer College.",False),
    ("California Chiropractic Association","Industrial Disability Evaluation, 1995–2002","Certification in industrial injury evaluation.",False)]},
  {"t":"photos","bg":"alt","eyebrow":"Federal certification","h2":"National Registry certificate","doc":True,"cols":1,
   "lede":"For the California licence (No. 18759, expiring 31 March 2027), please use the state lookup linked above — it shows the live status.",
   "items":[("license-fmcsa","FMCSA National Registry of Certified Medical Examiners certificate, number 5497424313","Issued 22 July 2019, valid through 22 July 2029")]},
  {"t":"photos","eyebrow":"In the treatment room","h2":"Dr. Chen at work",
   "items":[("dr-chen-adjusting","Dr. Chen performing a cervical adjustment",None),
            ("dr-chen-treating","Dr. Chen treating a patient at the adjusting table",None),
            ("certificates","Certificates and awards on the clinic wall",None)]},
  {"t":"table","bg":"alt","eyebrow":"Education and training","h2":"Background",
   "head":["Year","Item","Institution"],
   "rows":[["1987","Doctor of Chiropractic (D.C.)","Palmer College of Chiropractic"],
           ["—","Undergraduate","Northwest Missouri State University"],
           ["—","Manipulation Under Anaesthesia training","Texas Chiropractic College"],
           ["1995–2002","Industrial disability evaluation certification","California Chiropractic Association"],
           ["Current","Adjunct clinical faculty","Palmer College of Chiropractic"]]},
  {"t":"table","eyebrow":"Public service","h2":"Community and elected record",
   "lede":"These are public election and appointment records and can be checked with the relevant authority.",
   "head":["Year","Role"],
   "rows":[["2020–present","Board member, Alameda Health Care District"],
           ["2021–present","AC Transit district parcel tax oversight committee"],
           ["Former","Alameda City Council member"]]},
  {"t":"prose","bg":"alt","eyebrow":"Languages","h2":"You do not need to bring an interpreter",
   "html":"""<p>Dr. Chen speaks Cantonese, Mandarin, Taiwanese and English. That matters more in this setting than it might sound: describing pain accurately is difficult in a second language, and an imprecise history leads to an imprecise assessment.</p>
<p>Staff between them also cover Tagalog and Vietnamese, so front desk, billing and treatment can usually all be handled in the same language.</p>"""},
 ],
 "faqs":[
  ("How do I check the licence myself?","<p>Go to the California Department of Consumer Affairs licence search, choose Board of Chiropractic Examiners and licence type Chiropractor, and enter 18759 — digits only, without the DC prefix. The record shows the licensee name, status and expiry date.</p>",["dca_search","chiro_ca"]),
  ("What is a DOT certified medical examiner?","<p>A certified medical examiner is registered with the Federal Motor Carrier Safety Administration to perform commercial driver physicals. A driver's medical examination is only valid if performed by an examiner listed on the National Registry. You can confirm any examiner by searching their registry number.</p>",["fmcsa_srch",("int","/dot-physical/","About DOT physicals →")]),
  ("Which conditions does Dr. Chen see most often?","<p>Auto accident injuries, work-related back and neck injuries, sciatica, disc problems, and chronic neck and shoulder pain from desk work. Commercial drivers also come for DOT physicals.</p>",[("int","/services/","All services →")]),
 ],
 "related":[("/about/team/","Our team","Front desk, billing and treatment staff"),
            ("/dot-physical/","DOT / CDL physical","$95, same-day report"),
            ("/services/","All services","What the clinic treats")],
},

# ── 團隊 ─────────────────────────────────────────
{
 "slug":"about/team","crumbs":[("About","/about/")],"crumb_self":"Our team","cta_bg":"alt",
 "hero":("team","The CarePlus Chiropractic team"),
 "title":"Our Team｜CarePlus Chiropractic · Cantonese, Mandarin, Taiwanese, Tagalog, Vietnamese",
 "desc":"The CarePlus Chiropractic team covers front desk, insurance billing and treatment support, with languages including Cantonese, Mandarin, Taiwanese, Tagalog, Vietnamese and English.",
 "h1":"The people you will deal with",
 "answer":"Alongside Dr. Stewart Chen, the CarePlus team covers reception, insurance and claims paperwork, and treatment support. Between them the staff speak Cantonese, Mandarin, Taiwanese, Tagalog, Vietnamese and English, so scheduling, billing questions and treatment can usually all be handled in the same language.",
 "blocks":[
  {"t":"people","eyebrow":"Roles","h2":"Who does what",
   "items":[
    ("Clinical","Dr. Stewart Chen, D.C.","Examination, diagnosis, adjustment and treatment planning. California licence 18759; FMCSA certified medical examiner. <a class=\"int\" href=\"/about/dr-stewart-chen/\">Full credentials →</a>"),
    ("Front desk","Scheduling and new patient intake","Appointments, intake paperwork and first-visit questions, in Cantonese, Mandarin, Taiwanese, Tagalog, Vietnamese or English."),
    ("Insurance and claims","Billing and case paperwork","Verifying cover, handling correspondence with insurers, employers and attorneys, and preparing documentation for auto accident and workers' compensation cases."),
    ("Treatment support","Therapy and imaging assistance","Setting up therapy modalities, assisting with digital X-ray, and going through rehabilitation exercises with patients.")],
   "sources":["chiro_ca","aca"]},
  {"t":"note","kind":"","h":"Photographs of individual staff",
   "html":"<p>We are adding individual staff photographs to this page. Until then, the team photograph above is the current one.</p>"},
  {"t":"facts","bg":"alt","eyebrow":"Why this matters","h2":"Language cover across the whole visit",
   "items":[
    ("Reception","Booking and intake","Explaining what to bring and what will happen, before you arrive.",False),
    ("Clinical","History and examination","Describing pain precisely is hard in a second language, and an imprecise history leads to an imprecise assessment.",False),
    ("Billing","Insurance and claims","Auto accident and workers' compensation paperwork is where misunderstandings are most expensive.",False)]},
 ],
 "faqs":[
  ("Can I ask for a specific language when I book?","<p>Yes. Mention it when you call and we will make sure someone who speaks it is available for your visit.</p>",None),
  ("Who handles insurance questions?","<p>Our billing staff. If you are unsure whether your plan covers treatment here, call and ask for billing before your first visit — it is quicker to check in advance.</p>",[("int","/insurance/","Fees and insurance →")]),
 ],
 "related":[("/about/dr-stewart-chen/","Dr. Stewart Chen","Credentials and public record"),
            ("/new-patient/","New patients","What to bring to a first visit"),
            ("/contact/","Visit us","Directions, parking and hours")],
},

# ── 交通與預約 ───────────────────────────────────
{
 "slug":"contact","crumbs":[],"crumb_self":"Visit us","nap":True,"cta_bg":"",
 "hero":("storefront","The clinic entrance at 212 9th Street Suite 103, Oakland Chinatown"),
 "title":"Visit Us｜212 9th Street Suite 103, Oakland · Lake Merritt BART 5 min",
 "desc":"CarePlus Chiropractic is at 212 9th Street, Suite 103, Oakland CA 94607, a five-minute walk from Lake Merritt BART. Mon–Fri 9:00–18:00, Sat 9:00–12:00. Building and street parking. Call 510-465-7982.",
 "h1":"Getting here, parking and hours",
 "answer":"CarePlus Chiropractic is at 212 9th Street, Suite 103, Oakland CA 94607, in the Madison professional building between Jackson St and Alice St. It is a five-minute walk from Lake Merritt BART. Open Monday to Friday 9:00–18:00 and Saturday 9:00–12:00, closed Sunday. By appointment: 510-465-7982.",
 "blocks":[
  {"t":"facts","bg":"alt","eyebrow":"Getting here","h2":"Three ways to reach the clinic",
   "sources":["bart","actransit"],
   "items":[
    ("BART","Lake Merritt station, 5–7 min walk","Leave the station and head towards 9th Street. The clinic is in the Madison professional building, between Jackson St and Alice St.",False),
    ("Driving","Building and street parking","There is parking in the building and metered parking on the street. At busy times allow an extra 10 minutes.",False),
    ("AC Transit","Several downtown Oakland routes","Multiple lines stop within a few blocks of 9th Street in Chinatown.",False)]},
  {"t":"photos","eyebrow":"Finding the door","h2":"This is what the entrance looks like",
   "lede":"The clinic is on the ground floor of the Madison professional building, with a bilingual sign above the door.",
   "items":[("storefront-sign","The bilingual sign above the entrance: CHIROPRACTOR DR. STEWART CHEN",None),
            ("storefront-hours","Clinic hours displayed on the glass door",None),
            ("reception","Reception, just inside the entrance",None)]},
  {"t":"table","eyebrow":"Clinic hours","h2":"When we are open",
   "head":["Day","Hours"],
   "rows":[["Monday – Friday","9:00 – 18:00"],["Saturday","9:00 – 12:00"],["Sunday","Closed"]]},
  {"t":"note","kind":"warn","h":"By appointment","sources":["bart","actransit"],
   "html":"<p>The clinic works by appointment rather than walk-in. Please call <a href=\"tel:5104657982\">510-465-7982</a> before coming. If you cannot call right now, fill in the call-back form below and we will ring you during clinic hours.</p>"},
 ],
 "faqs":[
  ("Is there parking?","<p>Yes. There is parking in the Madison professional building and metered street parking nearby. During busy periods it is worth allowing an extra 10 minutes to find a space.</p>",None),
  ("Do you take walk-ins?","<p>The clinic works by appointment. Call 510-465-7982 and we will find a time. Saturday morning slots are available and tend to fill up first.</p>",None),
  ("Is the clinic accessible?","<p>The clinic is on the ground floor of the building. If you have specific access needs, please mention them when you call so we can make the necessary arrangements.</p>",None),
 ],
 "related":[("/new-patient/","New patients","What to bring to a first visit"),
            ("/dot-physical/","DOT / CDL physical","$95, same-day report"),
            ("/pricing/","Fees","Full price list")],
},

# ── 初診須知 ─────────────────────────────────────
{
 "slug":"new-patient","crumbs":[],"crumb_self":"New patients","cta_bg":"alt",
 "hero":("waiting-room","The CarePlus Chiropractic waiting room"),
 "title":"New Patients｜What to Bring and What Happens · CarePlus Chiropractic Oakland",
 "desc":"What to bring to your first visit at CarePlus Chiropractic in Oakland: photo ID, insurance card, and for accident or work injury cases the claim and report numbers. Allow 45 to 60 minutes.",
 "h1":"Your first visit",
 "answer":"Bring photo ID and your insurance card. For an auto accident or work injury, also bring the incident report number, the claim number and your attorney's details if you have representation. A first visit covers history, examination, digital X-ray where clinically indicated, and an explanation of findings. Allow 45 to 60 minutes.",
 "blocks":[
  {"t":"checklist","box":True,"eyebrow":"Bring with you","h2":"What to have ready",
   "items":["Photo ID","Insurance card","A list of any medication you are currently taking",
            "<strong>Auto accident:</strong> police report number, claim number, adjuster contact, attorney details if represented",
            "<strong>Work injury:</strong> employer details, date of injury, claim number, the DWC-1 form if you have it",
            "Any previous imaging or reports relating to this problem, if you have them"],
   "sources":["nccih_chiro","aca"]},
  {"t":"steps","bg":"alt","eyebrow":"What happens","h2":"How a first visit runs",
   "lede":"We do not begin treatment on first meeting you. The assessment comes first.",
   "items":[
    ("History — we listen first","Where the pain is, when it started, what makes it worse, previous injuries, and your work and sleep posture. For accident or work injury cases, how the incident happened."),
    ("Physical examination","Palpation, range of motion testing, and a neurological check of reflexes, strength and sensation, to work out whether the problem is structural, neurological or soft tissue."),
    ("Digital X-ray if indicated","Taken on site. Whether it is needed is a clinical judgement, not something every patient has."),
    ("Findings and plan explained","In the same visit you are told what was found, the likely cause, what is proposed and roughly how many visits it may take — before anything starts.")]},
  {"t":"photos","eyebrow":"Where you will be","h2":"Reception and waiting area",
   "items":[("reception","Reception, where you check in",None),
            ("hallway","The corridor to the treatment rooms",None)]},
  {"t":"facts","bg":"alt","eyebrow":"Practical","h2":"Things worth knowing beforehand",
   "items":[
    ("Time","Allow 45–60 minutes","A first visit takes longer than a follow-up because of the examination and the explanation.",False),
    ("Clothing","Comfortable, loose clothing","You may be asked to move through a range of positions during the examination.",False),
    ("Language","Tell us when you book","Cantonese, Mandarin, Taiwanese, Tagalog, Vietnamese and English are all available.",False),
    ("Payment","Depends on the route","Auto accident, workers' compensation, private insurance and self-pay each work differently.",False)]},
 ],
 "faqs":[
  ("Will I be treated on the first visit?","<p>Sometimes, but not always. The assessment comes first. If treatment is appropriate on the day and you want to go ahead, it can start then. If more information is needed first, we will say so.</p>",None),
  ("How many visits will I need?","<p>It depends on what the assessment shows. We give an estimate at the end of the first visit, and revise it as things progress. We would rather give you a range and explain the reasoning than quote a fixed number.</p>",None),
  ("Do I need a referral?","<p>No, a referral is not required to be seen here. Some insurance plans have their own requirements, so it is worth checking with your insurer if you intend to claim.</p>",[("int","/insurance/","Fees and insurance →")]),
 ],
 "related":[("/contact/","Visit us","Directions, parking and hours"),
            ("/insurance/","Fees and insurance","How payment works"),
            ("/services/","All services","What the clinic treats")],
},

]
