# -*- coding: utf-8 -*-
"""英文站服務頁。骨架與中文站相同：直答 → 這是什麼狀況 → 我們怎麼處理 →
費用來源 → 客觀條件 → 醫師資訊卡 → FAQ → 相關。
工傷頁不含 QME：2026-09-30 客戶確認該證書已失效、評估服務已停止；
工傷「治療」仍是本院主力項目，頁面保留並以此為主軸。"""

PAY_ROUTES_EN = [
 ("/insurance/auto-accident/","Auto accident","The at-fault driver's liability cover, MedPay on your own policy, or on a lien where you are represented.","What you need →"),
 ("/insurance/workers-comp/","Work injury","California workers' compensation — approved treatment is paid by the employer's insurer.","How it works →"),
 ("/insurance/ppo/","Private insurance","What PPO plans typically cover, and deductibles.","How to check →"),
 ("/insurance/self-pay/","Self-pay","Self-pay rates, including initial examination with digital X-ray.","See rates →"),
]

WHY_EN = [
 ("In practice since","1988 — 38 years","Same practitioner, same Oakland Chinatown block since 1988.",False),
 ("Languages","Cantonese · Mandarin · Taiwanese · English","From history-taking to explaining the plan, in the language you are most comfortable in.",False),
 ("On-site imaging","Digital X-ray, same visit","Where imaging is clinically indicated it is taken here, not at a separate centre.",False),
 ("Getting here","5 min from Lake Merritt BART","Madison professional building, downtown Oakland. Building and street parking.",False),
]

STEPS_EN = [
 ("History — we listen first","Where the pain is, when it started, what makes it worse, previous injuries, and your work and sleep posture. For accident or work injury cases, how the incident happened."),
 ("Physical examination","Palpation, range of motion testing, and a neurological check of reflexes, strength and sensation — to work out whether the problem is structural, neurological or soft tissue."),
 ("Digital X-ray if indicated","Taken on site. Whether it is needed is a clinical judgement, not a default for every patient."),
 ("Findings and plan explained","In the same visit you are told what was found, the likely cause, what is proposed and roughly how many visits it may take — before anything begins."),
]

BYLINE_EN = {
 "t":"byline","bg":"alt","alt":"Dr. Stewart Chen, D.C.",
 "name":"Treating clinician: Dr. Stewart Chen, D.C.",
 "note":'California chiropractic licence 18759 · FMCSA certified medical examiner · '
        'in practice in Oakland Chinatown since 1988　'
        '<a class="int" href="/about/dr-stewart-chen/">Full credentials and how to verify →</a>',
}

def svc_en(slug, h1, title, desc, answer, sname, sdesc, what_h2, what_html, what_src,
           methods, faqs, related, procedure=None, photos=None, hero=None, crumb_self=None):
    blocks = [
      {"t":"prose","eyebrow":"Understanding the problem","h2":what_h2,"html":what_html,"sources":what_src},
      {"t":"steps","bg":"alt","eyebrow":"What a first visit involves","h2":"How we work through it",
       "lede":"We do not begin treatment on first meeting you. The assessment comes first.",
       "items":STEPS_EN},
      {"t":"checklist","eyebrow":"What may be used","h2":"Combined according to the assessment",
       "lede":"Not every patient needs every item. What is used follows from what the examination shows.",
       "items":methods,"sources":["aca","nccih_back"]},
      {"t":"routes","bg":"alt","eyebrow":"Fees and insurance","h2":"Who usually pays for this",
       "lede":"How treatment is funded changes what paperwork you need. Pick the closest to your situation:",
       "items":PAY_ROUTES_EN},
      {"t":"facts","eyebrow":"Why here","h2":"A few objective points","items":WHY_EN},
      BYLINE_EN,
    ]
    if photos:
        blocks.insert(2, {"t":"photos","eyebrow":"At the clinic","h2":"Treatment rooms and equipment","items":photos})
    p = {
      "slug":"services/"+slug, "crumbs":[("Services","/services/")],
      "crumb_self":crumb_self or h1.split("|")[0].strip(),
      "title":title, "desc":desc, "h1":h1, "answer":answer, "cta_bg":"alt",
      "service":{"type":"MedicalProcedure" if procedure else "Service","name":sname,"desc":sdesc},
      "blocks":blocks, "faqs":faqs, "related":related, "faq_bg":"",
    }
    if hero: p["hero"] = hero
    if procedure: p["service"]["procedureType"] = procedure
    return p


PAGES = [

# ── 治療項目總覽 ─────────────────────────────────
{
 "slug":"services","crumbs":[],"crumb_self":"Services","cta_bg":"alt",
 "hero":("adjusting-table","An adjusting table in one of the treatment rooms"),
 "title":"Services｜Chiropractic, Acupuncture, Auto and Work Injury Rehab · Oakland",
 "desc":"Chiropractic adjustment, acupuncture, therapeutic massage, and rehabilitation for auto accident and work injuries, in Oakland Chinatown since 1988. On-site digital X-ray. Cantonese, Mandarin, Taiwanese and English.",
 "h1":"What the clinic treats",
 "answer":"CarePlus Chiropractic provides spinal adjustment, acupuncture, therapeutic massage and rehabilitation exercise, with particular experience in auto accident and work injury cases. Digital X-ray is available on site. The clinic has practised in Oakland Chinatown since 1988 and sees patients in Cantonese, Mandarin, Taiwanese and English.",
 "blocks":[
  {"t":"routes","eyebrow":"By situation","h2":"Start with what happened",
   "items":[
    ("/services/auto-injury/","Auto accident injury","Neck, back and shoulder injury after a collision, including symptoms that appear days later.","How this works →"),
    ("/services/work-injury/","Work injury","Assessment and treatment under California workers' compensation, with help on the paperwork.","What to expect →"),
    ("/services/lower-back-pain/","Low back pain","Persistent or recurring low back pain, with or without leg symptoms.","Read more →"),
    ("/services/neck-shoulder-pain/","Neck and shoulder pain","Including desk-work and screen-related neck pain.","Read more →"),
    ("/services/sciatica/","Sciatica","Pain, numbness or tingling running from the low back down the leg.","Read more →"),
    ("/dot-physical/","DOT / CDL driver physical","$95, report the same day, certified medical examiner.","Book →")]},
  {"t":"checklist","bg":"alt","eyebrow":"Methods","h2":"What may be used in treatment",
   "lede":"Combined according to what the assessment shows, not applied as a fixed package.",
   "items":["Chiropractic spinal adjustment","Acupuncture","Therapeutic and meridian massage",
            "Spinal traction","Ultrasound therapy","Electrical stimulation and microcurrent",
            "Cupping","Hot and cold therapy","Paraffin bath",
            "Rehabilitation exercise instruction","Posture and workstation advice"],
   "sources":["aca","nccih_back"]},
  {"t":"photos","eyebrow":"At the clinic","h2":"Treatment rooms and equipment",
   "items":[("exam-room","Examination room with diagnostic equipment and an X-ray viewer",None),
            ("xray-machine","The clinic's digital X-ray unit",None),
            ("traction-room","Treatment room with a traction table",None),
            ("massage-chair","Treatment room with adjusting table and massage chair",None)]},
  {"t":"facts","bg":"alt","eyebrow":"Why here","h2":"A few objective points","items":WHY_EN},
  BYLINE_EN,
 ],
 "faqs":[
  ("Do you take X-rays on site?","<p>Yes, digital X-ray is available in the clinic. Whether imaging is needed is a clinical judgement made during the examination — it is not taken as a matter of routine.</p>",None),
  ("Is chiropractic treatment appropriate for everyone?","<p>No. There are conditions where spinal manipulation is not indicated, which is why the examination comes first. If your presentation is better handled elsewhere, we will tell you.</p>",["nccih_back"]),
  ("Do you also offer acupuncture?","<p>Yes, acupuncture and therapeutic massage are both available, and are often used alongside adjustment rather than instead of it.</p>",[("int","/services/acupuncture/","Acupuncture →")]),
 ],
 "related":[("/dot-physical/","DOT / CDL physical","$95, same-day report"),
            ("/insurance/","Fees and insurance","How payment works"),
            ("/new-patient/","New patients","What to bring to a first visit")],
},

# ── DOT 體檢 ─────────────────────────────────────
{
 "slug":"dot-physical","crumbs":[],"crumb_self":"DOT / CDL physical","nap":True,"cta_bg":"alt",
 "hero":("exam-room","The examination room where DOT physicals are carried out"),
 "title":"DOT / CDL Driver Physical $95｜Oakland · Same-Day Report · Certified Examiner",
 "desc":"DOT/CDL commercial driver physical in Oakland at $95, performed by a certified medical examiner on the FMCSA National Registry (No. 5497424313). Report the same day, help submitting to the DMV. Saturday mornings available. 510-465-7982.",
 "h1":"DOT / CDL driver physical — $95, report the same day",
 "answer":"CarePlus Chiropractic performs DOT/CDL commercial driver physicals for $95, with the report issued the same day and help submitting it to the DMV. Dr. Stewart Chen is a certified medical examiner on the FMCSA National Registry, number 5497424313. The clinic is in Oakland Chinatown at 212 9th Street. Call 510-465-7982.",
 "blocks":[
  {"t":"price","eyebrow":"Price","h2":"$95, all inclusive",
   "amount":"$95","unit":"per exam",
   "items":["Performed by a DOT certified medical examiner","Report issued the same day",
            "We can help submit the report to the DMV","Saturday morning appointments available"],
   "note":"Under FMCSA rules a driver's medical certificate is valid for <strong>up to 24 months</strong>. Conditions such as high blood pressure or diabetes may shorten that to 12 or 3 months.",
   "sources":["fmcsa_reg","fmcsa_reg2"],
   "stamp":"Price current as of September 2026. Any additional testing is quoted before it is carried out."},
  {"t":"checklist","box":True,"eyebrow":"Bring with you","h2":"What to have ready",
   "items":["Driver's licence","A list of any medication you take, with dosages",
            "Glasses or contact lenses, if you wear them","Hearing aids, if you use them",
            "If you have a condition under treatment: a recent note or letter from the treating doctor",
            "If you use CPAP: your compliance report"]},
  {"t":"steps","bg":"alt","eyebrow":"On the day","h2":"How the examination runs",
   "items":[
    ("Health history","Current conditions, medication, surgical history, and anything that could affect safe operation of a commercial vehicle."),
    ("Vision and hearing","Acuity, peripheral vision and colour recognition; hearing tested to the federal standard."),
    ("Blood pressure and pulse","Blood pressure determines the certificate period, so it is worth arriving unhurried."),
    ("Urinalysis","Checks protein, sugar and specific gravity. This is <strong>not</strong> a drug test."),
    ("Physical examination","A general examination covering the systems required by the federal standard."),
    ("Certificate issued","Where you meet the standard, the certificate is issued the same day and we can help submit it.")]},
  {"t":"table","eyebrow":"Certificate period","h2":"What determines how long it lasts",
   "head":["Period","Typical reason"],
   "rows":[["24 months","Meets the standard with no condition requiring monitoring"],
           ["12 months","A condition that needs annual review, such as controlled hypertension"],
           ["3 months","Blood pressure requiring short-term recheck, or another condition needing close follow-up"],
           ["Not issued yet","Further specialist opinion or additional test results needed first"]],
   "sources":["fmcsa_reg","fmcsa_reg2"]},
  {"t":"note","kind":"warn","h":"A DOT physical is not a drug test",
   "html":"<p>These are <strong>two separate things</strong>. The urinalysis in a DOT physical checks protein, sugar and specific gravity — it is not a drug screen. If your employer also requires drug testing, say so when you book and we will explain how to arrange it.</p>"},
  {"t":"photos","eyebrow":"Where it happens","h2":"Examination room and equipment","cols":2,
   "items":[("exam-room","The examination room, with diagnostic equipment and X-ray viewer",None),
            ("xray-in-use","Clinic staff operating the on-site digital X-ray unit",None)]},
  {"t":"photos","bg":"alt","eyebrow":"Federal certification","h2":"National Registry certificate","doc":True,"cols":1,
   "lede":"A commercial driver's physical is only valid if performed by an examiner listed on the FMCSA National Registry.",
   "items":[("license-fmcsa","FMCSA National Registry certificate, number 5497424313","Issued 22 July 2019, valid through 22 July 2029. Searching that number on the registry returns this practice.")]},
 ],
 "faq_h2":"DOT physical — common questions",
 "faqs":[
  ("How long does it take?","<p>Most drivers are done in about 35 to 45 minutes, assuming no additional testing is needed. Booking ahead keeps the wait down.</p>",None),
  ("I have high blood pressure. Can I still be certified?","<p>Possibly, but the certificate period depends on the reading. FMCSA sets bands that correspond to different periods — some situations require the condition to be controlled and rechecked first. Bring your current medication list.</p>",["fmcsa_reg2"]),
  ("What if I do not pass?","<p>You are told exactly which criterion was not met and what would be needed. In many cases it is a matter of obtaining a specialist letter or bringing a condition under control, then being re-examined. We explain the route rather than simply declining.</p>",["fmcsa_reg2"]),
  ("My licence is from another state. Can I do the physical in California?","<p>Yes. The DOT physical is federal — it is valid if performed by an examiner on the FMCSA National Registry, regardless of state. Which state's DMV you submit the certificate to follows the rules of your licensing state.</p>",["fmcsa_srch"]),
  ("Do you do Saturday appointments?","<p>Yes, Saturday mornings from 9:00 to 12:00. These fill up faster than weekday slots, so book ahead where you can.</p>",None),
 ],
 "related":[("/about/dr-stewart-chen/","Dr. Stewart Chen","Credentials and how to verify them"),
            ("/contact/","Visit us","Directions, parking and hours"),
            ("/pricing/","Fees","Full price list")],
},
]

PAGES += [

svc_en("auto-injury",
 "Auto accident injury",
 "Auto Accident Injury Treatment｜Oakland · Neck, Back and Shoulder After a Collision",
 "Treatment for neck, back and shoulder injury after a car accident in Oakland. On-site digital X-ray, documentation for the claim, and billing usually through the at-fault insurer, MedPay or a lien. Cantonese, Mandarin, Taiwanese and English.",
 "After a collision, symptoms often appear later than the injury. Assessment covers the neck, mid and low back, with digital X-ray on site where indicated. Treatment is usually billed through the at-fault driver's liability cover, MedPay on your own policy, or on a lien if you are represented — not out of pocket.",
 "Auto accident injury rehabilitation",
 "Assessment and treatment of neck, back and shoulder injury following a motor vehicle collision, with documentation for insurance claims.",
 "Why symptoms can appear days after the accident",
 """<p>It is common to feel largely unhurt at the scene and to develop neck stiffness, headache or low back pain two or three days later. Adrenaline masks pain at the time, and soft-tissue inflammation takes time to build. A low-speed impact is not a reliable indicator of low injury — a collision at 5 mph can still displace cervical and lumbar segments, because the forces go through the spine regardless of how the vehicle looks afterwards.</p>
<p>The practical consequence is about timing rather than pain tolerance. The longer the gap between the accident and being examined, the easier it is for an insurer to argue the symptoms are unrelated. Being assessed within a week keeps the record clean, and gives you a baseline to measure recovery against.</p>""",
 ["nih_back","nccih_back"],
 ["Chiropractic adjustment of affected segments","Digital X-ray where clinically indicated",
  "Spinal traction","Electrical stimulation and microcurrent for muscle spasm",
  "Ultrasound therapy","Cold therapy in the acute phase, heat later",
  "Therapeutic massage for soft-tissue involvement","Rehabilitation exercise as the acute phase settles",
  "Written findings and progress notes for the claim file"],
 [("How soon after an accident should I be seen?","<p>Within a week where possible. Two reasons: delayed symptoms need to be assessed early, and the shorter the gap between the accident and examination, the harder it is to dispute that the injury is related.</p>",[("int","/insurance/auto-accident/","How auto accident billing works →")]),
  ("Do I have to pay up front?","<p>Usually not. Treatment after a collision in California is commonly paid by the at-fault driver's liability cover, by MedPay on your own policy, or on a lien where you are represented by an attorney, settled when the claim resolves. We go through which applies at the first visit.</p>",[("int","/insurance/auto-accident/","Auto accident claims →")]),
  ("What documents should I bring?","<p>The police report number, the claim number and the adjuster's contact details if you have them, plus your attorney's details if you are represented. If none of that has come through yet, come anyway — the assessment matters more than the paperwork, and the paperwork can follow.</p>",[("int","/new-patient/","New patient information →")]),
  ("I was told the damage was minor, so I can't be injured","<p>Vehicle damage and occupant injury do not track each other closely. A stiff bumper can transmit force to the occupant rather than absorbing it. What matters clinically is what the examination finds, not what the car looks like.</p>",None)],
 [("/insurance/auto-accident/","Auto accident claims","Liability cover, MedPay and liens"),
  ("/services/neck-shoulder-pain/","Neck and shoulder pain","Including whiplash-type injury"),
  ("/services/lower-back-pain/","Low back pain","Persistent and post-accident")],
 photos=[("xray-machine","The clinic's digital X-ray unit","Structural assessment after a collision, without a separate trip to an imaging centre"),
         ("dr-chen-adjusting","Dr. Chen performing a cervical adjustment",None)],
 hero=("xray-machine","The clinic's on-site digital X-ray unit")),

svc_en("work-injury",
 "Work injury",
 "Work Injury Treatment｜Oakland · California Workers' Compensation Cases",
 "Assessment and treatment of work-related back, neck, shoulder and repetitive strain injury in Oakland, under California workers' compensation, with help on the claim paperwork. Cantonese, Mandarin, Taiwanese and English.",
 "Work-related back, neck, shoulder and repetitive strain injuries are handled under California's workers' compensation system, where approved treatment is paid by the employer's insurer. The clinic provides assessment, treatment and the written documentation the claim requires, and can help with the correspondence.",
 "Work injury assessment and treatment",
 "Assessment and treatment of work-related musculoskeletal injury under the California workers' compensation system, including claim documentation.",
 "How a work injury claim works in California",
 """<p>If you are hurt at work in California, treatment normally comes under workers' compensation rather than your own health insurance, and approved care is paid by your employer's insurer. The sequence matters: report the injury to your employer, complete the DWC-1 claim form, and keep a copy of everything. Treatment is then generally arranged through the insurer's medical provider network, though there are exceptions — for example if you predesignated a personal physician before the injury.</p>
<p>Repetitive strain cases are often the hardest to get recognised, because there is no single incident to point to. Careful documentation of onset, work tasks and functional limitation does most of the work in those claims.</p>""",
 ["dwc_main","dwc_injured"],
 ["Chiropractic adjustment of affected segments","Digital X-ray where clinically indicated",
  "Electrical stimulation and microcurrent","Ultrasound therapy",
  "Therapeutic massage for soft-tissue involvement","Spinal traction",
  "Rehabilitation exercise and return-to-work conditioning",
  "Workstation and lifting technique advice",
  "Written findings, progress notes and functional documentation for the claim file"],
 [("Do I pay for treatment myself?","<p>Generally no. Under California workers' compensation, approved treatment for an accepted work injury is paid by the employer's insurer, not by you. Whether a particular treatment is approved depends on the insurer and the network, which is why the paperwork matters.</p>",["dwc_main",("int","/insurance/workers-comp/","Workers' compensation →")]),
  ("Can I choose my own doctor?","<p>It depends. If you predesignated a personal physician in writing before the injury, you can generally go to them. Otherwise treatment is usually arranged through the insurer's medical provider network. Bring whatever paperwork you have and we will help you work out where you stand.</p>",["dwc_injured"]),
  ("What should I bring to the first visit?","<p>Your employer's details, the date of injury, the claim number if one has been issued, and the DWC-1 form if you have it. If the claim is still being set up, come anyway — being assessed early helps the record.</p>",[("int","/new-patient/","New patient information →")]),
  ("My injury built up over time rather than from one incident","<p>That is still potentially a work injury. Repetitive strain claims turn on documentation: when symptoms began, which tasks are involved, how function is affected, and how it has progressed. We record that carefully from the first visit.</p>",["dwc_injured"])],
 [("/insurance/workers-comp/","Workers' compensation","The claims process explained"),
  ("/services/lower-back-pain/","Low back pain","Including lifting and posture-related"),
  ("/services/neck-shoulder-pain/","Neck and shoulder pain","Including desk-work strain")],
 photos=[("patient-in-treatment","A patient receiving treatment in one of the rooms",None),
         ("patient-files","The clinic's patient record files","Work injury claims run on documentation")]),

svc_en("lower-back-pain",
 "Low back pain",
 "Low Back Pain Treatment｜Oakland Chinatown · Assessment, X-ray and Rehabilitation",
 "Assessment and treatment of persistent and recurring low back pain in Oakland Chinatown. Examination, on-site digital X-ray where indicated, adjustment, traction and rehabilitation exercise. Cantonese, Mandarin, Taiwanese and English.",
 "Low back pain has several distinct causes, and the treatment that helps one will not help another. Assessment covers range of motion, neurological testing and digital X-ray where indicated, to distinguish between joint restriction, disc involvement, nerve irritation and soft-tissue strain before treatment begins.",
 "Low back pain assessment and treatment",
 "Examination, imaging where indicated, and treatment of acute and chronic low back pain.",
 "“Low back pain” is a symptom, not a diagnosis",
 """<p>The same complaint can come from a restricted joint, a disc pressing on a nerve root, a strained muscle, or referred pain from elsewhere. They feel broadly similar to the patient and respond to quite different treatment, which is why the examination comes before any hands-on work.</p>
<p>Two patterns are worth knowing. Pain that travels below the knee, or comes with numbness, tingling or weakness, suggests nerve involvement rather than a simple strain. And pain that is worse first thing and eases with movement behaves differently from pain that builds through the day — that distinction alone narrows the field considerably.</p>""",
 ["nih_back","nccih_back"],
 ["Chiropractic adjustment of restricted segments","Digital X-ray where clinically indicated",
  "Spinal traction where disc involvement is suspected","Electrical stimulation for muscle spasm",
  "Ultrasound therapy","Therapeutic massage","Hot and cold therapy",
  "Core and postural rehabilitation exercise","Lifting technique and workstation advice"],
 [("Should I rest or keep moving?","<p>For most mechanical low back pain, prolonged bed rest makes recovery slower rather than faster. Gentle movement within tolerance is usually better. What is appropriate for you depends on what the examination finds, so it is worth asking rather than guessing.</p>",["nih_back"]),
  ("When is low back pain something more serious?","<p>Certain features need prompt medical attention rather than conservative care: loss of bladder or bowel control, numbness in the saddle area, progressive weakness in a leg, unexplained weight loss, or pain following significant trauma. If any of these apply, seek medical care rather than booking a routine appointment.</p>",["nih_back"]),
  ("How many visits will I need?","<p>It depends on how long the problem has been there and what is causing it. We give an estimated range at the end of the first visit and revise it as we go, rather than quoting a fixed course in advance.</p>",None)],
 [("/services/sciatica/","Sciatica","When pain travels down the leg"),
  ("/services/herniated-disc/","Disc problems","Disc-related back pain"),
  ("/services/rehab-exercise/","Rehabilitation exercise","Strengthening and prevention")],
 photos=[("adjusting-table","An adjusting table in one of the treatment rooms",None),
         ("traction-room","Treatment room with a traction table",None)]),

svc_en("neck-shoulder-pain",
 "Neck and shoulder pain",
 "Neck and Shoulder Pain｜Oakland · Desk Work, Screen Posture and Whiplash",
 "Assessment and treatment of neck and shoulder pain in Oakland Chinatown, including desk-work and screen-related strain and post-collision whiplash. Cantonese, Mandarin, Taiwanese and English.",
 "Neck and shoulder pain frequently originates in the cervical spine rather than the shoulder itself, and can refer down the arm as numbness or tingling. Assessment distinguishes between cervical joint restriction, nerve root irritation and soft-tissue strain before treatment, with digital X-ray on site where indicated.",
 "Neck and shoulder pain assessment and treatment",
 "Examination and treatment of cervical and shoulder girdle pain, including postural and post-traumatic presentations.",
 "The shoulder that will not settle often is not the shoulder",
 """<p>Pain felt in the shoulder or upper arm commonly originates in the cervical spine. Nerve roots leaving the neck supply the shoulder and arm, so irritation there is felt further down. That is why shoulder treatment alone sometimes gives only temporary relief — the source has not been addressed.</p>
<p>Sustained forward head posture is the other common driver. Holding the head forward of the shoulders substantially increases the load carried by the neck extensors, and hours of that daily produces exactly the pattern seen in desk and phone users: tight upper trapezius, restricted cervical rotation, and headaches beginning at the base of the skull.</p>""",
 ["nih_back","nccih_back"],
 ["Cervical adjustment where indicated","Digital X-ray where clinically indicated",
  "Therapeutic massage for the upper trapezius and cervical musculature",
  "Electrical stimulation and microcurrent","Ultrasound therapy","Cupping","Hot and cold therapy",
  "Cervical traction where nerve involvement is suspected",
  "Postural correction and workstation adjustment advice","Rehabilitation exercise"],
 [("My arm goes numb — is that coming from my neck?","<p>Often yes. Numbness or tingling travelling down the arm usually indicates nerve root involvement in the cervical spine rather than a local shoulder problem. The examination includes reflex, strength and sensation testing to establish which nerve level is involved.</p>",["nih_back"]),
  ("I sit at a screen all day. Is there anything I can change?","<p>Yes, and it is usually worth more than treatment alone. Screen height, chair support and how often you change position all matter. We go through your specific setup rather than giving generic advice.</p>",[("int","/services/rehab-exercise/","Rehabilitation exercise →")]),
  ("I had whiplash from a car accident years ago and it still bothers me","<p>Untreated or partly treated whiplash can leave lasting restriction. It is still assessable now — the examination looks at current range of motion and neurological status rather than at how long ago the incident was.</p>",[("int","/services/auto-injury/","Auto accident injury →")])],
 [("/services/headache-dizziness/","Headache and dizziness","Cervicogenic presentations"),
  ("/services/auto-injury/","Auto accident injury","Whiplash-type injury"),
  ("/services/rehab-exercise/","Rehabilitation exercise","Posture and strengthening")],
 photos=[("adjusting-table","An adjusting table in one of the treatment rooms",None),
         ("patient-in-treatment","A patient receiving treatment in one of the rooms",None)]),

svc_en("sciatica",
 "Sciatica",
 "Sciatica Treatment｜Oakland · Leg Pain, Numbness and Tingling from the Low Back",
 "Assessment and treatment of sciatica in Oakland Chinatown: pain, numbness or tingling travelling from the low back into the buttock and leg. Digital X-ray on site where indicated. Cantonese, Mandarin, Taiwanese and English.",
 "Sciatica describes pain, numbness or tingling travelling from the low back through the buttock and down the leg, caused by irritation of the sciatic nerve. Assessment establishes where along its course the nerve is being affected, since disc-related and muscular causes respond to different treatment.",
 "Sciatica assessment and treatment",
 "Examination and treatment of sciatic nerve irritation, including disc-related and piriformis-related presentations.",
 "Sciatica is a description of symptoms, not the cause of them",
 """<p>The sciatic nerve runs from the low back through the buttock and down the back of the leg. Pressure anywhere along that path produces similar symptoms, but the cause determines the treatment. A disc pressing on a nerve root in the low back and a tight piriformis muscle compressing the nerve in the buttock can feel much the same to the patient and need quite different handling.</p>
<p>Two features guide the assessment: how far down the leg symptoms travel, and whether there is weakness as well as pain. Symptoms below the knee, or any loss of strength, point to nerve root involvement and change both the urgency and the approach.</p>""",
 ["nih_back","nccih_back"],
 ["Chiropractic adjustment of the lumbar and sacroiliac region",
  "Digital X-ray where clinically indicated","Spinal traction where disc involvement is suspected",
  "Soft-tissue work on the piriformis and gluteal musculature",
  "Electrical stimulation and microcurrent","Ultrasound therapy","Cold and heat therapy",
  "Nerve mobilisation and stretching","Rehabilitation exercise"],
 [("How is disc-related sciatica different from a muscular cause?","<p>Broadly, disc-related sciatica tends to be worse with sitting, coughing or straining, and more often produces symptoms below the knee. Piriformis-related sciatica is often worse with prolonged sitting on a hard surface and more localised to the buttock and thigh. The examination distinguishes them properly — these are tendencies, not rules.</p>",["nih_back"]),
  ("Is there anything that means I should not wait?","<p>Yes. Loss of bladder or bowel control, numbness in the saddle area, or progressive weakness in the leg need urgent medical attention rather than a routine appointment. Please seek medical care immediately if any of those apply.</p>",["nih_back"]),
  ("Will I need surgery?","<p>Most sciatica resolves without surgery. Conservative care is generally the first approach. Where the examination suggests something that needs a surgical opinion, we say so and refer rather than continuing.</p>",["nccih_back"])],
 [("/services/lower-back-pain/","Low back pain","Where sciatica often originates"),
  ("/services/herniated-disc/","Disc problems","Disc-related nerve compression"),
  ("/services/rehab-exercise/","Rehabilitation exercise","Preventing recurrence")],
 photos=[("traction-in-use","Traction equipment in use",None),
         ("adjusting-table","An adjusting table in one of the treatment rooms",None)]),
]

PAGES += [

svc_en("herniated-disc",
 "Disc problems",
 "Herniated and Bulging Disc｜Oakland · Assessment, Traction and Rehabilitation",
 "Assessment and conservative treatment of herniated and bulging discs in Oakland Chinatown, including traction and rehabilitation. On-site digital X-ray where indicated.",
 "A bulging or herniated disc can press on a nearby nerve root, producing pain, numbness or weakness that travels away from the spine. Assessment establishes which level is involved and whether conservative care is appropriate, with imaging on site where clinically indicated.",
 "Disc injury assessment and treatment",
 "Conservative assessment and treatment of intervertebral disc injury, including traction and rehabilitation.",
 "A disc problem is not automatically a surgical problem",
 """<p>Discs sit between the vertebrae and act as spacers and shock absorbers. When the outer wall weakens, the inner material can push outward — a bulge — and in some cases through it, a herniation. The symptom depends on whether that displaced material contacts a nerve root, and which one.</p>
<p>The important point is that a disc finding on imaging does not by itself determine treatment. Many people have disc changes visible on imaging and no symptoms at all. What matters is whether the clinical picture matches the imaging, which is why examination comes first and imaging second.</p>""",
 ["nih_back","nccih_back"],
 ["Digital X-ray where clinically indicated","Spinal traction to reduce pressure on the affected segment",
  "Chiropractic adjustment of adjacent restricted segments","Electrical stimulation for associated spasm",
  "Ultrasound therapy","Cold therapy in the acute phase",
  "Graded rehabilitation exercise","Advice on lifting, sitting and sleeping position"],
 [("Do I need an MRI?","<p>Not always. X-ray shows alignment and bone; MRI shows soft tissue including the disc itself. Where the examination suggests MRI would change management, we say so and refer. Imaging for its own sake rarely helps.</p>",["nih_back"]),
  ("Will I need surgery?","<p>Most disc problems settle with conservative care. Surgery is generally considered where there is progressive neurological loss, or where conservative care has been given a fair trial without improvement. Where the examination suggests a surgical opinion is needed, we refer.</p>",["nccih_back"]),
  ("Is adjustment safe with a disc problem?","<p>It depends on the presentation, which is exactly why the examination comes first. There are disc presentations where manipulation of the affected segment is not appropriate, and the approach is adjusted accordingly.</p>",["nccih_back"])],
 [("/services/sciatica/","Sciatica","When disc pressure affects the leg"),
  ("/services/lower-back-pain/","Low back pain","Broader assessment"),
  ("/services/rehab-exercise/","Rehabilitation exercise","Preventing recurrence")],
 photos=[("traction-room","Treatment room with a traction table",None),
         ("xray-machine","The clinic's digital X-ray unit",None)]),

svc_en("rehab-exercise",
 "Rehabilitation exercise",
 "Rehabilitation Exercise｜Oakland · Strengthening, Posture and Preventing Recurrence",
 "Rehabilitation exercise instruction at CarePlus Chiropractic in Oakland: graded strengthening, postural correction and workstation advice, so improvement holds after treatment ends.",
 "Treatment relieves the immediate problem; rehabilitation exercise is what stops it returning. Programmes are graded to what the examination shows, covering strengthening, mobility and posture, with workstation advice where the problem is work-related.",
 "Rehabilitation exercise programme",
 "Graded rehabilitation exercise, postural correction and ergonomic advice following musculoskeletal injury.",
 "Why the problem keeps coming back",
 """<p>Pain that resolves and then returns a few months later usually means the cause was not addressed, only the symptom. If the underlying pattern — weak deep stabilisers, restricted mobility somewhere else, a workstation that forces a poor position for eight hours a day — is unchanged, the tissue goes back under the same load and fails in the same way.</p>
<p>Rehabilitation is the part that changes that. It is less dramatic than treatment and it depends on the patient doing it, which is why programmes here are kept short and specific rather than long and generic.</p>""",
 ["nih_back","nccih_back"],
 ["Assessment of movement pattern and functional limitation",
  "Graded strengthening for the affected region","Mobility and stretching work",
  "Core and deep stabiliser activation","Postural correction",
  "Workstation and ergonomic advice","Lifting technique","Return-to-work conditioning where relevant"],
 [("How long do I need to keep doing the exercises?","<p>Through the acute phase at minimum, and for recurring problems, as maintenance. We would rather give you three exercises you will actually do than twelve you will not.</p>",None),
  ("Do I need equipment?","<p>Mostly no. Programmes are built around what you can do at home or at your desk. Where a resistance band or similar would help, we say so and it is inexpensive.</p>",None),
  ("What if the exercises hurt?","<p>Tell us. Mild discomfort during rehabilitation is normal; sharp or increasing pain is not. The programme should be adjusted rather than pushed through.</p>",None)],
 [("/services/lower-back-pain/","Low back pain","Assessment and treatment"),
  ("/services/neck-shoulder-pain/","Neck and shoulder pain","Posture-related presentations"),
  ("/services/work-injury/","Work injury","Return-to-work conditioning")],
 photos=[("traction-in-use","Traction equipment in use",None),
         ("patient-in-treatment","A patient receiving treatment",None)],
 hero=("traction-in-use","Traction equipment in use at the clinic")),

svc_en("headache-dizziness",
 "Headache and dizziness",
 "Cervicogenic Headache and Dizziness｜Oakland · When the Neck Is the Source",
 "Assessment of headache and dizziness arising from the cervical spine at CarePlus Chiropractic in Oakland. Examination distinguishes neck-related presentations from those needing medical referral.",
 "Some headaches and some dizziness originate in the cervical spine rather than in the head itself. Assessment identifies whether the pattern fits a cervicogenic cause, and equally importantly whether it does not — some presentations need medical rather than chiropractic assessment.",
 "Cervicogenic headache assessment",
 "Assessment and treatment of headache and dizziness arising from cervical spine dysfunction.",
 "Not every headache comes from the head",
 """<p>The upper cervical joints share nerve pathways with structures in the head, so restriction or irritation there can be felt as headache — typically beginning at the base of the skull and spreading forward, often on one side, and often worse after sustained desk or screen work. Dizziness can arise the same way, since the upper neck contributes to balance information.</p>
<p>The examination matters as much for what it rules out as what it finds. Headache with sudden severe onset, with neurological changes, with fever, or following head trauma needs medical assessment rather than chiropractic care, and we will say so.</p>""",
 ["nih_back","nccih_back"],
 ["Cervical examination including range of motion and neurological testing",
  "Upper cervical adjustment where indicated","Soft-tissue work on the suboccipital and cervical musculature",
  "Electrical stimulation and microcurrent","Heat therapy",
  "Postural correction and workstation adjustment","Rehabilitation exercise for the deep neck flexors"],
 [("When should I see a doctor instead?","<p>Sudden severe headache unlike any you have had before, headache with fever or neck rigidity, headache with vision changes, weakness or confusion, or headache following a head injury — these need medical assessment, not chiropractic care. Please seek medical attention.</p>",["nih_back"]),
  ("How do I know if my headache is coming from my neck?","<p>Typical features include onset at the base of the skull, one-sidedness, a link with sustained posture, and restricted neck movement. The examination tests those directly rather than relying on the description alone.</p>",None),
  ("Can neck treatment help dizziness?","<p>Where the dizziness is cervicogenic, sometimes. There are many other causes of dizziness — inner ear, blood pressure, medication — that are not treatable this way, and the examination is partly about distinguishing them.</p>",["nccih_back"])],
 [("/services/neck-shoulder-pain/","Neck and shoulder pain","The usual underlying cause"),
  ("/services/auto-injury/","Auto accident injury","Post-collision headache"),
  ("/services/rehab-exercise/","Rehabilitation exercise","Posture work")],
 photos=[("dr-chen-adjusting","Dr. Chen performing a cervical adjustment",None),
         ("exam-room","Examination room with diagnostic equipment",None)]),

svc_en("acupuncture",
 "Acupuncture",
 "Acupuncture｜Oakland Chinatown · Alongside Chiropractic Care at CarePlus",
 "Acupuncture at CarePlus Chiropractic in Oakland Chinatown, used alongside chiropractic care for musculoskeletal pain. Cantonese, Mandarin, Taiwanese and English.",
 "Acupuncture is offered at the clinic and is most often used alongside chiropractic care rather than instead of it, particularly where muscle tension and pain persist after the structural component has been addressed. Whether it is appropriate follows from the assessment.",
 "Acupuncture",
 "Acupuncture for musculoskeletal pain, used alongside chiropractic assessment and treatment.",
 "How acupuncture fits alongside chiropractic care",
 """<p>Chiropractic care addresses joint restriction and its effects on the nervous system. Acupuncture works on a different level, and in practice the two are often complementary: the adjustment restores movement, and acupuncture helps with the muscular tension and pain that can persist around it.</p>
<p>It is not offered as a standalone answer to every presentation. Whether it is used, and how often, follows from the examination — the same as every other modality here.</p>""",
 ["nccih_back","aca"],
 ["Assessment of where muscular involvement is contributing",
  "Acupuncture for associated muscle tension and pain","Cupping","Meridian and therapeutic massage",
  "Combined with chiropractic adjustment where indicated","Heat therapy"],
 [("Does it hurt?","<p>Most people describe a dull ache or heaviness rather than sharp pain. The needles are very fine. If something is uncomfortable, say so and it is adjusted.</p>",None),
  ("How many sessions will I need?","<p>It depends on the presentation and how long it has been there. We give an estimate after the assessment and revise it as we go.</p>",None),
  ("Can I have acupuncture and chiropractic on the same visit?","<p>Often yes, and it is a common combination here. Whether it makes sense for you follows from the assessment.</p>",[("int","/services/","All services →")])],
 [("/services/massage-therapy/","Massage therapy","Soft-tissue treatment"),
  ("/services/neck-shoulder-pain/","Neck and shoulder pain","Common presentation"),
  ("/services/","All services","What the clinic treats")],
 photos=[("therapy-device","Therapy equipment at the clinic",None)]),

svc_en("massage-therapy",
 "Massage therapy",
 "Therapeutic Massage｜Oakland Chinatown · Soft Tissue Work at CarePlus Chiropractic",
 "Therapeutic and meridian massage at CarePlus Chiropractic in Oakland Chinatown, used alongside chiropractic care for muscular tension and soft-tissue involvement.",
 "Therapeutic and meridian massage is used at the clinic for the muscular and soft-tissue component of musculoskeletal problems, generally alongside chiropractic care rather than as a standalone treatment. What is used follows from the assessment.",
 "Therapeutic massage",
 "Therapeutic and meridian massage for soft-tissue involvement in musculoskeletal conditions.",
 "Muscle and joint problems usually travel together",
 """<p>When a joint has been restricted for a while, the muscles around it adapt — some tighten, others weaken. Treating only the joint leaves that pattern in place, and it tends to pull things back towards where they were. Treating only the muscle leaves the restriction that caused the tension in the first place.</p>
<p>So massage here is generally used as part of the plan rather than as the plan. How much, and where, depends on what the examination found.</p>""",
 ["nccih_back","aca"],
 ["Assessment of soft-tissue involvement","Therapeutic massage for affected musculature",
  "Meridian massage","G5 percussion massage","Cupping","Heat therapy and paraffin bath",
  "Combined with chiropractic adjustment where indicated"],
 [("Is this the same as a relaxation massage?","<p>No. The purpose here is clinical — addressing specific muscular involvement identified during the examination — rather than general relaxation.</p>",None),
  ("Will it be painful?","<p>Work on a tight area can be uncomfortable, but it should not be sharply painful. Tell the therapist and the pressure is adjusted.</p>",None)],
 [("/services/acupuncture/","Acupuncture","Often used alongside"),
  ("/services/neck-shoulder-pain/","Neck and shoulder pain","Common presentation"),
  ("/services/","All services","What the clinic treats")],
 photos=[("cupping","Dr. Chen performing cupping therapy",None),
         ("massage-chair","Treatment room with adjusting table and massage chair",None)]),

svc_en("pediatric-spine",
 "Paediatric spinal assessment",
 "Children's Spinal Assessment｜Oakland · Posture, Growth and Backpack Load",
 "Spinal assessment for children and adolescents at CarePlus Chiropractic in Oakland Chinatown: posture, growth-related changes, backpack load and screen use. Cantonese, Mandarin, Taiwanese and English.",
 "Children are assessed differently from adults. During growth, posture, backpack load and screen use all affect the developing spine, and problems that are easy to address early become harder later. Assessment is age-appropriate and the approach is adjusted accordingly.",
 "Paediatric spinal assessment",
 "Age-appropriate spinal assessment for children and adolescents.",
 "Why assessment during growth is different",
 """<p>A growing spine responds differently from an adult one. Postural habits established during school years — a heavy pack carried on one shoulder, hours bent over a screen, a chair the wrong height — act on tissue that is still developing, and small asymmetries can become established.</p>
<p>The flip side is that the same adaptability makes early changes easier to influence. Assessment during growth is mostly about noticing patterns early and changing the load, not about treating children like small adults.</p>""",
 ["nccih_back","aca"],
 ["Age-appropriate postural and spinal assessment","Screening for asymmetry and curvature",
  "Backpack weight and carrying advice","Desk, chair and screen height advice",
  "Gentle age-appropriate treatment where indicated","Exercise and stretching guidance for children"],
 [("At what age can a child be assessed?","<p>There is no fixed lower limit — what changes is the approach. Assessment and, where appropriate, treatment are adapted to the child's age and size.</p>",None),
  ("Should my child be X-rayed?","<p>Only where there is a specific clinical reason. We are more conservative about imaging in children, not less.</p>",None),
  ("My child's backpack seems very heavy","<p>It is a common factor. As a general guide, a pack carried on both shoulders and kept to a modest proportion of body weight is much better tolerated than a heavy one on one shoulder. We can go through it specifically.</p>",[("int","/services/scoliosis/","Scoliosis assessment →")])],
 [("/services/scoliosis/","Scoliosis","Curvature assessment"),
  ("/services/neck-shoulder-pain/","Neck and shoulder pain","Screen-related in teenagers"),
  ("/about/","About the clinic","How we work")],
 photos=[("exam-room","Examination room with diagnostic equipment",None)]),

svc_en("scoliosis",
 "Scoliosis",
 "Scoliosis Assessment｜Oakland · Curvature Monitoring and Conservative Care",
 "Scoliosis assessment at CarePlus Chiropractic in Oakland Chinatown: curvature measurement with on-site digital X-ray, monitoring over time, and conservative management.",
 "Scoliosis is a sideways curvature of the spine, most often identified during adolescent growth. Assessment establishes the degree of curvature and whether it is changing, which is what determines management. Digital X-ray is available on site for measurement and monitoring.",
 "Scoliosis assessment",
 "Assessment, measurement and monitoring of spinal curvature, with conservative management where appropriate.",
 "What matters is whether the curve is changing",
 """<p>A single measurement says less than a series of them. Many curves are mild and stable and need monitoring rather than intervention; others progress during growth spurts and need closer attention. Establishing which you are dealing with requires measurement over time, which is why imaging and record-keeping matter here more than usual.</p>
<p>Conservative care can help with the pain, muscular imbalance and postural consequences that accompany a curve. Where a curve is significant or progressing, it needs an orthopaedic opinion, and we refer rather than manage it alone.</p>""",
 ["nih_back","nccih_back"],
 ["Postural assessment and curvature screening","Digital X-ray for measurement where indicated",
  "Monitoring over time to establish whether the curve is changing",
  "Treatment of associated muscular imbalance and pain","Rehabilitation and postural exercise",
  "Referral for orthopaedic opinion where indicated"],
 [("Can chiropractic care straighten a scoliosis?","<p>No, and anyone telling you otherwise is overstating it. Conservative care can help with pain, muscular imbalance and function, and monitoring matters — but it does not correct the curve itself. Significant or progressing curves need an orthopaedic opinion.</p>",["nih_back"]),
  ("How often should a curve be monitored?","<p>During growth, more often than after it. The interval depends on the degree of curvature and whether it has changed. We set it case by case rather than by a fixed rule.</p>",None),
  ("My child was screened at school — what now?","<p>A school screening flags a possible curve; it does not measure it. The next step is measurement, which needs imaging. Bring whatever the school gave you.</p>",[("int","/services/pediatric-spine/","Children's spinal assessment →")])],
 [("/services/pediatric-spine/","Children's spinal assessment","Posture and growth"),
  ("/services/lower-back-pain/","Low back pain","Associated symptoms"),
  ("/services/rehab-exercise/","Rehabilitation exercise","Postural work")],
 photos=[("xray-in-use","Clinic staff operating the digital X-ray unit","Curvature measurement needs imaging"),
         ("exam-room","Examination room with diagnostic equipment",None)]),

svc_en("sports-injury",
 "Sports injury",
 "Sports Injury｜Oakland · Assessment, Treatment and Return to Activity",
 "Sports injury assessment and treatment at CarePlus Chiropractic in Oakland Chinatown, covering acute injury and overuse, with graded return to activity.",
 "Sports injuries divide broadly into acute injury and overuse. The distinction matters because they need different handling: acute injury needs early protection and graded loading, while overuse needs the underlying cause found and changed, or it recurs.",
 "Sports injury assessment and treatment",
 "Assessment and treatment of acute and overuse sports injuries, with graded return to activity.",
 "Acute injury and overuse are different problems",
 """<p>An acute injury has a moment — a landing, a twist, a collision. An overuse injury does not; it builds up because tissue is loaded repeatedly faster than it recovers. The management differs accordingly. For acute injury, the early question is what was damaged and how much it should be loaded. For overuse, treating the painful tissue without changing what caused the overload simply resets the clock.</p>
<p>Returning to activity too early is the most common reason an injury becomes a recurring one. Graded return matters as much as the treatment itself.</p>""",
 ["nih_back","nccih_back"],
 ["Assessment of the injured region and contributing mechanics",
  "Digital X-ray where clinically indicated","Chiropractic adjustment where indicated",
  "Soft-tissue and therapeutic massage","Electrical stimulation and ultrasound therapy",
  "Cold therapy acutely, heat later","Graded rehabilitation and return-to-activity programme"],
 [("How soon can I get back to training?","<p>It depends on the tissue and the injury. We give a graded plan rather than a single date, because returning at full load too early is the main reason injuries recur.</p>",None),
  ("Do I need imaging?","<p>Only where the examination suggests it would change management — for example where a fracture needs ruling out. It is not routine.</p>",None),
  ("My injury keeps coming back","<p>That usually points to an underlying mechanical cause that has not been addressed — a movement pattern, a strength imbalance, or a training load issue. Recurring injury is worth assessing differently from a first-time one.</p>",[("int","/services/rehab-exercise/","Rehabilitation exercise →")])],
 [("/services/rehab-exercise/","Rehabilitation exercise","Graded return to activity"),
  ("/services/lower-back-pain/","Low back pain","Common in lifting sports"),
  ("/services/","All services","What the clinic treats")],
 photos=[("patient-in-treatment","A patient receiving treatment",None),
         ("therapy-device","Therapy equipment at the clinic",None)]),
]
